import Head from "next/head";
import React, { Fragment, useEffect, useState } from "react";
import Sidebar from "./sidebar";
import { useRouter } from "next/router";
import Header from "./header";
import DataLoader from "../ui/dataLoader";

export default function Layout({ children, title }) {

    const router = useRouter();
    const [loading, setLoading] = useState(true); // Add loading state

    useEffect(() => {
        const authToken = localStorage.getItem("authToken");
        if (!authToken) {
            router.push("/"); // Redirect if no token
        } else {
            setLoading(false); // Token found, stop loading
        }
    }, [router]);

    if (loading) {
        return <DataLoader />; // Show loader while checking token
    }
    return (
        <Fragment>
            <Head>

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex min-h-screen relative">
                <Sidebar />

                <div className="flex flex-1 flex-col lg:pl-64 bg-white">
                    <Header title={title} />
                    {children}
                </div>

            </div>
        </Fragment>
    );
};

